language: python
python:
  - "2.7"
install:
  - pip install pip==6.1.1
  - pip install -r requirements_local.txt
script:
  - sudo mkdir -m 777 /var/lib/anytask/
  - cd /var/lib/anytask/
  - git clone https://github.com/gebetix/repos
  - cd znick/anytask/anytask
  - python manage.py test courses tasks issues
