sudo: required
language: python
python:
  - "3.8"
install:
  - pip install pip>=9.0.1
  - pip install --upgrade flake8
  - pip install -r requirements_local.txt
  - sudo apt-get install p7zip-full tar xz-utils bzip2 gzip
  - sudo apt-get install python3
script:
  - sudo mkdir -m 777 /var/lib/anytask/
  - cd /var/lib/anytask/
  - git clone https://github.com/gebetix/repos
  - cd ~/build/znick/anytask/anytask
  - flake8 --version
  - flake8
  - python manage.py test
