# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Anytask tests

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-20.04

    services:
      minio:
        image: fclairamb/minio-github-actions
        ports:
          - 9000:9000

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        pip install pip>=9.0.1
        pip install --upgrade flake8 'setuptools-scm==5.0.2'
        pip install -r requirements_local.txt
        sudo apt-get install p7zip-full tar xz-utils bzip2 gzip
    - name: Lint with flake8
      run: |
        cd anytask
        flake8 --version
        flake8
    - name: Create MinIO test bucket
      run: |
        s3cmd --no-ssl --access_key minioadmin --secret_key minioadmin \
          --host localhost:9000 --host-bucket localhost:9000 \
          mb s3://anytask-test-s3
    - name: Run django tests
      run: |
        cd anytask
        python manage.py test
